node26.cluster
/home/unibas/boittier/FDCM/fbuta_2/0_1
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-0-1.xyz’: No such file or directory

real	0m1.085s
user	0m0.388s
sys	0m0.011s
-xyz
refined.xyz
-dens
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/1_SCAN_1_2_3_4_F/B.d.cube
-esp
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/1_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "refined.xyz" for reading
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/1_2
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-1-2.xyz’: No such file or directory

real	0m1.845s
user	0m0.380s
sys	0m0.012s
-xyz
refined.xyz
-dens
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/2_SCAN_1_2_3_4_F/B.d.cube
-esp
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/2_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "refined.xyz" for reading
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/2_3
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-2-3.xyz’: No such file or directory

real	0m1.756s
user	0m0.388s
sys	0m0.009s
-xyz
refined.xyz
-dens
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/3_SCAN_1_2_3_4_F/B.d.cube
-esp
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/3_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "refined.xyz" for reading
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/3_4
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-3-4.xyz’: No such file or directory

real	0m2.092s
user	0m0.376s
sys	0m0.017s
-xyz
refined.xyz
-dens
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/4_SCAN_1_2_3_4_F/B.d.cube
-esp
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/4_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "refined.xyz" for reading
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/4_5
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-4-5.xyz’: No such file or directory

real	0m1.991s
user	0m0.379s
sys	0m0.012s
-xyz
refined.xyz
-dens
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/5_SCAN_1_2_3_4_F/B.d.cube
-esp
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/5_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "refined.xyz" for reading
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/5_6
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-5-6.xyz’: No such file or directory

real	0m1.805s
user	0m0.375s
sys	0m0.016s
-xyz
refined.xyz
-dens
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/6_SCAN_1_2_3_4_F/B.d.cube
-esp
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/6_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "refined.xyz" for reading
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/6_7
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-6-7.xyz’: No such file or directory

real	0m1.866s
user	0m0.372s
sys	0m0.017s
-xyz
refined.xyz
-dens
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/7_SCAN_1_2_3_4_F/B.d.cube
-esp
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/7_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "refined.xyz" for reading
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/7_8
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-7-8.xyz’: No such file or directory

real	0m1.678s
user	0m0.380s
sys	0m0.012s
-xyz
refined.xyz
-dens
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/8_SCAN_1_2_3_4_F/B.d.cube
-esp
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/8_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "refined.xyz" for reading
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/8_9
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-8-9.xyz’: No such file or directory

real	0m1.152s
user	0m0.387s
sys	0m0.011s
-xyz
refined.xyz
-dens
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/9_SCAN_1_2_3_4_F/B.d.cube
-esp
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/9_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "refined.xyz" for reading
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/9_10
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-9-10.xyz’: No such file or directory

real	0m0.395s
user	0m0.388s
sys	0m0.005s
-xyz
refined.xyz
-dens
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/10_SCAN_1_2_3_4_F/B.d.cube
-esp
/home/unibas/boittier/RDKit_G2/B.pdb/SCAN_1_2_3_4_S_36_10.0/10_SCAN_1_2_3_4_F/B.p.cube
-stepsize
0.2
-n_steps
100
-learning_rate
0.5
ERROR: Could not open "refined.xyz" for reading
cp: cannot stat ‘refined.xyz’: No such file or directory
/home/unibas/boittier/FDCM/fbuta_2/10_11
Traceback (most recent call last):
  File "/home/unibas/boittier/AdjustReference-System/ARS.py", line 432, in <module>
    ARS_obj = ARS(xyz_file_name, pcube, frame_file, pcube2=pcube_2)
TypeError: __init__() got an unexpected keyword argument 'pcube2'
cp: cannot stat ‘fbuta_2-10-11.xyz’: No such file or directory
slurmstepd: error: *** JOB 38322408 ON node26 CANCELLED AT 2021-10-01T10:40:04 ***
